# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-28 14:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Назва предмету')),
                ('lector_name', models.CharField(max_length=256, verbose_name='Ім’я викладача')),
                ('date', models.DateTimeField(null=True, verbose_name='Дата та час проведення')),
            ],
            options={
                'verbose_name_plural': 'Екзамени',
                'verbose_name': 'Екзамен',
            },
        ),
    ]
