# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-28 14:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exams', '0001_initial'),
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='exam_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='groups.Group', verbose_name='Група'),
        ),
    ]
